# Mosquitto Configuration for Waveme
# Allow all connections
allow_anonymous true

# Standard MQTT for ESP32
listener 1883 0.0.0.0

# WebSockets for Mobile App
listener 9001 0.0.0.0
protocol websockets
